config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :books do
    get :search, on: :collection
  end

  resources :publishers
  resources :editors
  resources :comments
  resources :reviews
  resources :customers
  resources :categories
  resources :locations
  resources :dashboards
  resources :orders
  root to: 'books#index'
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  # Schema Information
    # t.string "name"
    # t.string "address"
	has_many :books
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :find_publisher, only: %i[show edit update destroy]
  def index
  	@publishers = Publisher.all
  end
  
  def show
  end

  def new
  	@publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    flash[:success] = "You've already successfully created #{@publisher.name}"
  	if @publisher.save
  		redirect_to publishers_path
  	else
  		render :new
  	end
  end

  def edit
  end
 
  def update
  	if @publisher.update_attributes(publisher_params)
      flash[:success] = "You've already successfully updated #{@publisher.name}"
  		redirect_to publisher_path(@publisher)
  	else
  		render :edit
  	end
  end

  def destroy
    @publisher.destroy
    flash[:danger] = "You've already successfully deleted #{@publisher.name}"
    redirect_to publishers_path
  end

  private
    def find_publisher
      @publisher = Publisher.find(params[:id])
    end

    def publisher_params
    	params.require(:publisher).permit(:name, :address)
    end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_action.html.erb
<%= link_to publisher_path(publisher) do %>
  <i class="fa fa-eye" title="Show"></i>
<% end %>
<%= link_to edit_publisher_path(publisher) do %>
  <i class="fa fa-edit" title="Edit"></i>
<% end %>
<%= link_to publisher_path(publisher), method: :delete, data: { confirm: "Are you sure? "} do %>
  <i class="fa fa-trash" title="Destroy">
<% end %>

app/views/publishers/_form.html.erb
<div class="col-8 offset-2">
  <%= simple_form_for @publisher do |f| %>
    <%= f.input :name, label: false, placeholder: "Please input name" %>
    <%= f.input :address, label: false, placeholder: "Please input address" %>
    <%= f.submit "Create", class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/publishers/edit.html.erb
<h1 class="text-center text-primanry"> Edit publisher</h1>
<%= render 'form' %>

app/views/publishers/index.html.erb
<h2 class="text-center text-primary">Listing of Publishers</h2>
<div class="col-8 offset-2">
<%= link_to 'New Publisher', new_publisher_path, class: "badge badge-pill badge-primary" %>
  <table class="table table-striped">
    <thead class="border-off">
      <tr class="text-center text-primary">
        <th>No</th>
        <th class="text-right">Name</th>
        <th class="text-left">Address</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @publishers.each_with_index do |publisher,index| %>
        <tr class="text-center text-primary">
          <td><%= index +1 %></td>
          <td class="text-right"><%= publisher.name %></td>
          <td class="text-left"><%= publisher.address %></td>
          <td><%= render 'action', publisher: publisher %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/publishers/new.html.erb
<h1 class="text-center text-primary"> New Publisher </h1>
<%= render 'form' %>

app/views/publishers/show.html.erb
<% if @publisher.present? %>
  <h1>publisher <%= @publisher.address %></h1>
  <h1>publisher <%= @publisher.name %></h1>

  <p>
    <%= @publisher.address %>
  </p>

  <p>
	<%= @publisher.name %>
  </p>
  <%= link_to 'Edit', edit_publisher_path(@publisher) %>
 
<% end %>

<h3> quanttity of books :<%=@publisher.books.count%></h3>
<% @publisher.books.each do |book| %>
  <p>
    <%= book.title %>
    <% if book.persisted? %>
      <%= link_to 'Destroy', book_path(book), method: :delete %>
   <% end %>
  </p>

<% end %>

<p>book here</p>