config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :books do
    get :search, on: :collection
  end

  resources :publishers
  resources :editors
  resources :comments
  resources :reviews
  resources :customers
  resources :categories
  resources :locations
  resources :dashboards
  resources :orders
  root to: 'books#index'
end

app/models/book.rb
class Book < ApplicationRecord
	# Schema Information
	# t.string "title"
	# t.string "author"
	# t.text "description"
	# t.integer "publisher_id"
	# t.integer "view_count", default: 0
	# t.float "price", default: 0.0
	# t.integer "quantity", default: 0
	# t.string "category_id"
	# t.datetime "created_at", null: false
	# t.datetime "updated_at", null: false
	max_paginates_per 25
	validates_presence_of :title
	belongs_to :publisher
	belongs_to :category
	has_many :comments
	has_many :books_locations
	has_many :locations, through: :books_locations

	def increase_view_count
		update_column(:view_count, view_count + 1)
	end

	def self.search(search)
    search ? self.where('title ILIKE ?', "%#{search}%") : self
  end
end

app/models/books/category_id.rb
class Books::CategoryId < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: %i[show edit update destroy]
  def index
    if params[:order] == 'name'
      @books = Book.order('title ASC').page params[:page]
    elsif params[:order] == 'id' # ordered by views_count
      @books = Book.order('id ASC').page params[:page]
    elsif params[:search].present?
      @books = Book.search(params[:search]).page params[:page]
    else
      @books = Book.order('view_count DESC').page params[:page]
    end
  end

  def show
  	@comment = @book.comments.new
    # iincrease view count
    @book.increase_view_count
  end
 
  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	if @book.save
      flash[:success] = "You've already successfully created #{@book.title}"
  		redirect_to books_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @book.update_attributes(book_params)
      flash[:success] = "You've already successfully updated #{@book.title}"
  		redirect_to book_path(@book)
  	else
  		render :edit
  	end
  end

  def destroy
  	@book.destroy
    flash[:danger] = "You've already successfully deleted #{@book.title}"
  	redirect_to books_path
  end


  private
    def find_book
      @book = Book.find(params[:id])
    end

    def book_params
    	params.require(:book).permit(:author, :title, :description, :publisher_id, :category_id, :price, :quantity)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_action.html.erb
<%= link_to book_path(book) do %>
  <i class="fa fa-eye" title="Show"></i>
<% end %>
<%= link_to edit_book_path(book) do %>
  <i class="fa fa-edit" title="Edit"></i>
<% end %>
<%= link_to book_path(book), method: :delete, data: { confirm: "Are you sure? "} do %>
  <i class="fa fa-trash" title="Destroy">
<% end %>

app/views/books/_form.html.erb
<div class="col-8 offset-2">
  <%= simple_form_for @book do |f|%>
    <%= f.input :title, label: false, placeholder: " Please input title" %>
    <%= f.input :author, label: false, placeholder: " Please input author" %>
    <%= f.input :description, label: false, placeholder: " Please input description" %>
    <%= f.input :price, label: false %>
    <%= f.input :quantity, label: false %>
    <%= f.input :publisher, collection: Publisher.pluck(:name, :id) %>
    <%= f.input :category, collection: Category.pluck(:name, :id) %>
    <%= f.submit "Create", class: 'btn btn-primary btn-block btn-lg' %>
  <% end %>
</div> 

app/views/books/_table.html.erb
<div class="container-fluid px-0">
  <table class="table table-striped">
    <thead class="thead-inverse">
      <tr class="border-off text-center text-primary">
        <th class="text-center text-primary">No.</th>
        <th>Title</th>
        <th>View count</th>
        <th>Author</th>
        <th>Description</th>
        <th>Publisher</th>
        <th>Category</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each_with_index do |book, index| %>
        <tr class="text-center text-primary">
          <td class="text-center text-primary"><%= index+1 %></td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td class="text-center text-primary"><%= book.view_count %></td>
          <td><%= book.author %></td>
          <td><%= book.description %></td>
          <td class="px-0">
            <% if book.publisher.present? %>
              <%= book.publisher.name %>
            <% end %>
          </td>
          <td >
            <% if book.category.present? %>
              <%= book.category.name %>
            <% end %>
          </td>
          <td class="px-0"><%= render 'action', book: book %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/edit.html.erb
<h1 class="text-center text-primary"> Edit Book</h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h2 class="text-center text-primary">Listing of Books</h2>
<div class="col-8 offset-2">
  <%= link_to 'New Book', new_book_path, class: "badge badge-pill badge-primary" %>
  <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sort by <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Sort by name', books_path(order: 'name'), class: 'padding-left' %></li>
      <li><%= link_to 'Sort by views count', books_path(order: 'views_count'), class: 'padding-left' %></li>
      <li><%= link_to 'Sort by time', books_path(order: 'id'), class: 'padding-left' %></li>
    </ul>
  </div>
  <br>
  <span class="float-right"><%= paginate @books, window: 2  %></span> 
  <%= render 'table', book: @book %>
  <span class="float-right"><%= paginate @books, window: 2  %></span> 
</div>

app/views/books/new.html.erb
<h1 class="text-center text-primary">Create New Book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<h1>Book <%= @book.title %> (View counts: <%= @book.view_count %>)</h1>

<p>
  <%= @book.author %>
</p>

<p>
	<%= @book.description %>
</p>

<p> Price:
  <%= @book.price %>
</p>

<p> Quantity:
  <%= @book.quantity %>
</p>

<% if @book.publisher.present? %>
  <p>Publisher name: <%= @book.publisher.name %></p>
<% end %>

<%= link_to 'Edit', edit_book_path(@book) %>
<%= link_to 'Destroy', book_path(@book), method: :delete %>

<h3>Locations</h3>
<ul>
<% @book.locations.each do |location| %>
  <li>
    <%= location.name %> 
    <%= location.district %> 
  </li>
</ul>
<% end %>

<p>Comment here</p>
<%= form_for @comment do |f| %>
  <%= f.hidden_field :book_id %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

<h3>Comments</h3>
<% @book.comments.each do |comment| %>
  <p>
  	<%= comment.content %>
  	<% if comment.persisted? %>
	  	<%= link_to 'Destroy', comment_path(comment), method: :delete %>
	 <% end %>
  </p>

<% end %>