config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :books do
    get :search, on: :collection
  end

  resources :publishers
  resources :editors
  resources :comments
  resources :reviews
  resources :customers
  resources :categories
  resources :locations
  resources :dashboards
  resources :orders
  root to: 'books#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	# Schema Information
	# t.string "title"
	# t.string "author"
	# t.text "description"
	# t.integer "publisher_id"
	# t.integer "view_count", default: 0
	# t.float "price", default: 0.0
	# t.integer "quantity", default: 0
	# t.string "category_id"
	# t.datetime "created_at", null: false
	# t.datetime "updated_at", null: false
	max_paginates_per 25
	validates_presence_of :title
	belongs_to :publisher
	belongs_to :category
	has_many :comments
	has_many :books_locations
	has_many :locations, through: :books_locations

	def increase_view_count
		update_column(:view_count, view_count + 1)
	end

	def self.search(search)
    search ? self.where('title ILIKE ?', "%#{search}%") : self
  end
end

app/models/books_location.rb
class BooksLocation < ApplicationRecord
  # Schema Information
  # t.integer "book_id"
  # t.integer "location_id"
	belongs_to :book
	belongs_to :location
end

app/models/category.rb
class Category < ApplicationRecord
  # Schema Information
  # t.string "name"
	has_many :books
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Schema Information
    # t.text "content"
    # t.integer "book_id"
	belongs_to :book
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/editor.rb
class Editor < ApplicationRecord
  # Schema Information
    # t.string "name"
    # t.string "phone"
    # t.integer "birth_year"
	has_many :reviews
end

app/models/location.rb
class Location < ApplicationRecord
  # Schema Information
    # t.string "name"
    # t.string "street"
    # t.string "address"
    # t.string "district"
	has_many :books_locations
	has_many :books, through: :books_locations
end

app/models/order.rb
class Order < ApplicationRecord
  # Schema Information
    # t.integer "quantity"
    # t.string "book"
    # t.string "customer"
    # t.float "total_price"
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  # Schema Information
    # t.string "name"
    # t.string "address"
	has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  # Schema Information
    # t.text "content"
    # t.integer "editor_id"
	belongs_to :editor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Schema Information
    # t.string "name"
    # t.string "sex"
    # t.integer "age"
    # t.string "address"
    # t.string "email", default: "", null: false
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: %i[show edit update destroy]
  def index
    if params[:order] == 'name'
      @books = Book.order('title ASC').page params[:page]
    elsif params[:order] == 'id' # ordered by views_count
      @books = Book.order('id ASC').page params[:page]
    elsif params[:search].present?
      @books = Book.search(params[:search]).page params[:page]
    else
      @books = Book.order('view_count DESC').page params[:page]
    end
  end

  def show
  	@comment = @book.comments.new
    # iincrease view count
    @book.increase_view_count
  end
 
  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	if @book.save
      flash[:success] = "You've already successfully created #{@book.title}"
  		redirect_to books_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @book.update_attributes(book_params)
      flash[:success] = "You've already successfully updated #{@book.title}"
  		redirect_to book_path(@book)
  	else
  		render :edit
  	end
  end

  def destroy
  	@book.destroy
    flash[:danger] = "You've already successfully deleted #{@book.title}"
  	redirect_to books_path
  end


  private
    def find_book
      @book = Book.find(params[:id])
    end

    def book_params
    	params.require(:book).permit(:author, :title, :description, :publisher_id, :category_id, :price, :quantity)
    end
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  before_action :find_editor, only: %i[show update edit destroy]
	def index
	  @editors = Editor.all
	end

  def show
    @review = @editor.reviews.new
	end

  def new
	 @editor = Editor.new
	end

	def create
  	@editor = Editor.new(editor_params)
  	if @editor.save
      flash[:success] = "You've already successfully created #{@editor.name}"
  		redirect_to editors_path
  	else
  		render :new
  	end
  end
  
	def edit
	end

	def update
  	if @editor.update_attributes(editor_params)
      flash[:success] = "You've already successfully updated #{@editor.name}"
  		redirect_to editor_path(@editor)
  	else
  		render :edit
  	end
  end

  def destroy
    @editor.destroy
    flash[:danger] = "You've already successfully deleted #{@editor.name}"
    redirect_to editors_path
  end

  private
    def find_editor
      @editor = Editor.find(params[:id])
    end
    
  	def editor_params
  	  params.require(:editor).permit(:name, :phone, :birth_year)
  	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: %i[show edit update destroy]
  def index
  	@orders = Order.all
  end
  
  def show
  end

  def new
  	@order = Order.new
  end

  def create
  	@order = Order.new(order_params)
  	if @order.save
      flash[:success] = "You've already successfully created order"
  		redirect_to orders_path
  	else
  		render :new
  	end
  end

  def edit
  end
 
  def update
  	if @order.update_attributes(order_params)
      flash[:success] = "You've already successfully updated order"
  		redirect_to order_path(@order)
  	else
  		render :edit
  	end
  end

  def destroy
    @order.destroy
    flash[:danger] = "You've already successfully deleted order"
    redirect_to orders_path
  end

  private
    def find_order
      @order = Order.find(params[:id])
    end

    def order_params
    	params.require(:order).permit(:quantity, :book, :book_id, :customer, :customer_id, :total_price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show edit update destroy]
  def index
  	@users = User.all
  end

  def show
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to users_path
      flash[:success] = "You've already successfully created #{@user.name}"
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @user.update_attributes(user_params)
  		redirect_to user_path(@user)
      flash[:success] = "You've already successfully updated #{@user.name}"
  	else
  		render :edit
  	end
  end

  def destroy
  	@user.destroy
  	redirect_to users_path
    flash[:success] = "You've already successfully deleted #{@user.name}"
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
    	params.require(:user).permit(:name, :sex, :age, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/editors/_action.html.erb
<%= link_to editor_path(editor) do %>
  <i class="fa fa-eye" title="Show"></i>
<% end %>
<%= link_to edit_editor_path(editor) do %>
  <i class="fa fa-edit" title="Edit"></i>
<% end %>
<%= link_to editor_path(editor), method: :delete, data: { confirm: "Are you sure? "} do %>
  <i class="fa fa-trash" title="Destroy">
<% end %>

app/views/editors/_form.html.erb
<div class="col-8 offset-2">
  <%= simple_form_for @editor do |f| %>
    <%= f.input :name, label: false, placeholder: "Please input name" %>
    <%= f.input :phone, label: false, placeholder: "Please input phone" %>
    <%= f.input :birth_year, label: false, placeholder: "Please input birth year" %>
    <%= f.submit "Create", class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/editors/edit.html.erb
<h1 class="text-center text-primary"> Edit Editors List</h1>
<%= render 'form' %>

app/views/editors/index.html.erb
<div class="col-8 offset-2">
<h1 class="text-center text-primary">Listing of Editors</h1>
<%= link_to 'New Editor', new_editor_path, class:"badge badge-pill badge-primary"  %>
  <table class="table table-striped">
    <thead class="border-off">
      <tr class="text-center text-primary">
        <th>No</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Birth Year</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @editors.each_with_index do |editor,index| %>
        <tr class="text-center text-primary">
          <td><%= index +1 %></td>
          <td><%= editor.name %></td>
          <td><%= editor.phone %></td>
          <td><%= editor.birth_year %></td>
          <td><%= render 'action', editor: editor %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/editors/new.html.erb
<h1 class="text-center text-primary"> Editors</h1>
<%= render 'form' %>

app/views/editors/show.html.erb
<h1>editor <%= @editor.name %></h1>

<p>
  <%= @editor.phone %>
</p>

<p>
	<%= @editor.birth_year %>
</p>

<% if @editor.present? %>
  <p>editor name: <%= @editor.name %></p>
<% end %>

<%= link_to 'Edit', edit_editor_path(@editor) %>
<%= link_to 'Destroy', editor_path(@editor), method: :delete %>

<h3>Reviews</h3>
<% @editor.reviews.each do |review| %>
  <p>
  	<%= review.content %>
  	<% if review.persisted? %>
	  	<%= link_to 'Destroy', review_path(review), method: :delete %>
	 <% end %>
  </p>

<% end %>

<p>Review here</p>
<%= form_for @review do |f| %>
  <%= f.hidden_field :editor_id %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/orders/index.html.erb
<h2>Order List</h2>

<%= link_to 'New orders', new_order_path  %>

<% @orders.each do |order| %>

    	<h3><%= link_to order.quantity, order_path(order) %></h3>
    	<p><%= order.book_id %></p>
    	<p><%= order.customer_id %></p>
    	<p><%= order.total_price %></p>
    	
  <% end %>

app/views/users/_form.html.erb
<div class="col-8 offset-2">
  <%= simple_form_for @user do |f| %>
    <%= f.input :name, label: false, placeholder: "Please input name" %>
    <%= f.input :age, label: false, placeholder: "Please input age" %>
    <%= f.input :address, label: false, placeholder: "Please input address" %>
    <%= f.input :sex, :collection => [['Man',1],['Woman',2]] %>
    <%= f.submit "Create User", class: 'btn btn-primary btn-block' %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center text-primary"> Edit user</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h2>User List</h2>

<%= link_to 'New users', new_user_path  %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Sex</th>
      <th>Age</th>
      <th>Address</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user,index| %>
      <tr>
        <td><%= index +1 %></td>
        <td><%= user.name %></td>
        <td><%= user.sex %></td>
        <td><%= user.age %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to "Edit", edit_user_path(user)%></td>
        <td><%= link_to "Destroy", user_path(user),
                method: :delete,
                data: { confirm: "Are you sure? "} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1 class="text-center text-primary"> New user </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
  <div class="card-header">Profile</div>
  <div class="card-body">
    <h5 class="card-title"><h1>Name: <%= @user.name %></h1></h5>
    <h5 class="card-title"><h1>Sex: <%= @user.sex %></h1></h5>
    <h5 class="card-title"><h1>Age: <%= @user.age %></h1></h5>
    <h5 class="card-title"><h1>Address: <%= @user.address %></h1></h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <%= link_to 'Edit', edit_user_path(@user), class: "badge badge-pill badge-primary" %>
    <%= link_to 'Destroy', user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "badge badge-pill badge-primary"  %>
  </div>
</div> 