config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :books do
    get :search, on: :collection
  end

  resources :publishers
  resources :editors
  resources :comments
  resources :reviews
  resources :customers
  resources :categories
  resources :locations
  resources :dashboards
  resources :orders
  root to: 'books#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	# Schema Information
	# t.string "title"
	# t.string "author"
	# t.text "description"
	# t.integer "publisher_id"
	# t.integer "view_count", default: 0
	# t.float "price", default: 0.0
	# t.integer "quantity", default: 0
	# t.string "category_id"
	# t.datetime "created_at", null: false
	# t.datetime "updated_at", null: false
	max_paginates_per 25
	validates_presence_of :title
	belongs_to :publisher
	belongs_to :category
	has_many :comments
	has_many :books_locations
	has_many :locations, through: :books_locations

	def increase_view_count
		update_column(:view_count, view_count + 1)
	end

	def self.search(search)
    search ? self.where('title ILIKE ?', "%#{search}%") : self
  end
end

app/models/books_location.rb
class BooksLocation < ApplicationRecord
  # Schema Information
  # t.integer "book_id"
  # t.integer "location_id"
	belongs_to :book
	belongs_to :location
end

app/models/category.rb
class Category < ApplicationRecord
  # Schema Information
  # t.string "name"
	has_many :books
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Schema Information
    # t.text "content"
    # t.integer "book_id"
	belongs_to :book
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/editor.rb
class Editor < ApplicationRecord
  # Schema Information
    # t.string "name"
    # t.string "phone"
    # t.integer "birth_year"
	has_many :reviews
end

app/models/location.rb
class Location < ApplicationRecord
  # Schema Information
    # t.string "name"
    # t.string "street"
    # t.string "address"
    # t.string "district"
	has_many :books_locations
	has_many :books, through: :books_locations
end

app/models/order.rb
class Order < ApplicationRecord
  # Schema Information
    # t.integer "quantity"
    # t.string "book"
    # t.string "customer"
    # t.float "total_price"
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  # Schema Information
    # t.string "name"
    # t.string "address"
	has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  # Schema Information
    # t.text "content"
    # t.integer "editor_id"
	belongs_to :editor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Schema Information
    # t.string "name"
    # t.string "sex"
    # t.integer "age"
    # t.string "address"
    # t.string "email", default: "", null: false
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: %i[show edit update destroy]
  def index
    if params[:order] == 'name'
      @books = Book.order('title ASC').page params[:page]
    elsif params[:order] == 'id' # ordered by views_count
      @books = Book.order('id ASC').page params[:page]
    elsif params[:search].present?
      @books = Book.search(params[:search]).page params[:page]
    else
      @books = Book.order('view_count DESC').page params[:page]
    end
  end

  def show
  	@comment = @book.comments.new
    # iincrease view count
    @book.increase_view_count
  end
 
  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	if @book.save
      flash[:success] = "You've already successfully created #{@book.title}"
  		redirect_to books_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @book.update_attributes(book_params)
      flash[:success] = "You've already successfully updated #{@book.title}"
  		redirect_to book_path(@book)
  	else
  		render :edit
  	end
  end

  def destroy
  	@book.destroy
    flash[:danger] = "You've already successfully deleted #{@book.title}"
  	redirect_to books_path
  end


  private
    def find_book
      @book = Book.find(params[:id])
    end

    def book_params
    	params.require(:book).permit(:author, :title, :description, :publisher_id, :category_id, :price, :quantity)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show edit update destroy]
  def index
  	@users = User.all
  end

  def show
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to users_path
      flash[:success] = "You've already successfully created #{@user.name}"
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @user.update_attributes(user_params)
  		redirect_to user_path(@user)
      flash[:success] = "You've already successfully updated #{@user.name}"
  	else
  		render :edit
  	end
  end

  def destroy
  	@user.destroy
  	redirect_to users_path
    flash[:success] = "You've already successfully deleted #{@user.name}"
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
    	params.require(:user).permit(:name, :sex, :age, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/layouts/_messages.html.erb
<div class="container-fluid text-center px-0">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> my-0 py-0">
      <a href="#" data-dismiss="alert" class="close">×</a>
        <ul class="my-1 bullet-off">
          <li>
            <%= value %>
          </li>
        </ul>
    </div>
  <% end %>
</div>
  

app/views/layouts/_navbar.html.erb
<div class="container-fluid px-0">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div >
      <%= form_tag books_path, class: 'navbar-form navbar-left', method: :get do %>
        <div class="form-inline">
          <%= text_field_tag :search, params[:search], :class =>"form-control", :placeholder=>"Search" %>
        </div>
      <% end %>
    </div>
   
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Books", books_path,           class: "dropdown-item" %>
            <%= link_to "Publishers", publishers_path, class: "dropdown-item" %>
            <%= link_to "Editors", editors_path,       class: "dropdown-item" %>
            <%= link_to "Customers", customers_path,   class: "dropdown-item" %>
            <%= link_to "Categories", categories_path, class: "dropdown-item" %>
            <%= link_to "Locations", locations_path,   class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboards_path,  class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Orders", orders_path,         class: "dropdown-item" %>
          </div>
        </li>
      </ul>
      
      <div class="float-right">
        <% if user_signed_in? %>
          <li class="navbar-nav ">
            <a href="#"><%=link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link text-danger'%></a>
          </li>
        <% else %>
          <li class="nav-item">
            <a  href="#"><%= link_to "Sign In", new_user_session_path, class: "nav-link text-primary"%></a>
          </li>

          <li class="nav-item">
            <a href="#"><%=link_to 'Sign Up', new_user_registration_path, class: "nav-link text-primary"%></a>
          </li>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('Book-Blank-Book-icon.png') %>
  </head>

  <body>
    <%= render 'layouts/navbar' %> 
  	<%= render 'layouts/messages' %> 
    <%= yield %>
  </body>
</html>